name: Bug Report
description: File a reproducible bug report
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report an issue!
  - type: input
    id: package
    attributes:
      label: Affected Package or App
      description: Which app or package is affected? (e.g. apps/website-builder-platform, packages/component-library)
      placeholder: apps/website-builder-platform
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run '...'
        2. Execute '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true
