name: Feature Request
description: Suggest an idea or architectural improvement
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: Thank you for proposing a feature or architectural enhancement!
  - type: textarea
    id: feature-description
    attributes:
      label: Problem or Feature Proposal
      description: Is your feature request related to a problem or new capability?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution or architecture you'd like to see implemented.
    validations:
      required: true
